# Generated by Django 3.1.2 on 2020-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoches', '0002_remove_coches_url_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='coches',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coches',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coches',
            name='precio_oferta',
            field=models.IntegerField(default=0),
        ),
    ]
