# Generated by Django 3.1.2 on 2020-11-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoches', '0003_auto_20201126_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coches',
            old_name='año',
            new_name='anno',
        ),
    ]
